/// <reference lib="webworker" />
import { Serwist } from '@serwist/core';
import { precacheAndRoute } from '@serwist/precache';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from '@serwist/strategies';
import { ExpirationPlugin } from '@serwist/expiration';
import { CacheableResponsePlugin } from '@serwist/cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build process.
// The Serwist webpack plugin will inject the manifest here.
precacheAndRoute(self.__SW_MANIFEST);

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
});

// Cache strategy for HTML pages (Next.js pages/routes)
// NetworkFirst ensures fresh content but falls back to cache quickly.
serwist.addRouter(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200], // Cache successful responses and opaque responses
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  }),
);

// Cache strategy for static assets (JS, CSS, images, fonts)
// CacheFirst is good for assets that don't change often.
serwist.addRouter(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style' ||
    request.destination === 'image' ||
    request.destination === 'font',
  new CacheFirst({
    cacheName: 'assets-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  }),
);

// Cache strategy for API calls (e.g., flight data)
// StaleWhileRevalidate provides fast access to cached data while updating in the background.
// This aligns with the "Offline First" and "faster than airline announcements" mission.
serwist.addRouter(
  ({ url }) => url.pathname.startsWith('/api/'),
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60, // 1 hour for API data, as per CLAUDE.md (Flight info = 60s, Airline info = 24h, but a general API cache can be longer)
        // Note: Specific API routes might need more granular caching configured in Next.js API routes themselves (e.g., Vercel KV).
        // This SW cache acts as a secondary, client-side cache.
      }),
    ],
  }),
);

// Fallback for offline pages
serwist.setDefaultHandler(
  new NetworkFirst({
    cacheName: 'default-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  }),
);

// Optional: Add a custom offline page
// serwist.addRouter(
//   ({ request }) => request.mode === 'navigate' && !navigator.onLine,
//   new CacheFirst({
//     cacheName: 'offline-page-cache',
//     plugins: [
//       new CacheableResponsePlugin({
//         statuses: [0, 200],
//       }),
//     ],
//   }).handle({ request: new Request('/offline') }), // Assuming you have an /offline page
// );

// Listen for messages from the client to skip waiting
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    void self.skipWaiting();
  }
});

serwist.install();
serwist.activate();
serwist.cleanupOutdatedCaches();

